### ISSUE TITLE
Arrival screen does not show the name of site after first

### ISSUE THREAD

**Issue by doctor-g** [spring2017gamestudio/prairie-creek#26]
Proposed revisions to the map screen may result in the removal of `arrival-screen`, which would make this issue no longer worth pursuing.  However, I wanted to log the issue as I walk through the game and find problems.

**Comment by doctor-g** [comment]
I am having some trouble reproducing this defect. Sometimes I see it and sometimes not. I think @DylonPrice had described something like this in our meeting yesterday. Can you clarify if you have some idea how to reproduce or where it is coming from?

**Comment by zmbube** [comment]
I believe the source of this was after visiting the first site it will send you back to the arrival-view upon leaving the range of the site and having no currentSite causing it to display the arrival screen with no site name.  I believe this is because when checking currentSite upon it changing it does a null check when it actually gets set to undefined.

**Comment by zmbube** [comment]
I have pushed a solution I believe works to the branch show-arrival-view-on-site-only
